tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'JDIFKO'
      role: developer
      database: JDIFKO_DB
      schema: DEV
      warehouse: play_xs
      threads: 8
    prod:
      type: snowflake
      account: 'not needed'
      user: 'JDIFKO'
      role: developer
      database: JDIFKO_DB
      schema: PROD
      warehouse: play_xs
      threads: 8
